### PR TITLE
Fix default server image for servers on hetzner cloud

### LINKED ISSUE #99: Creating a new instance on Hetznercloud fails with "image not found"
Since today, the autoscaler is unable to provision new instances on hetzner cloud. The drone cli tells me the ubuntu 16.04 image could not be found:

```
$ drone server info $(drone server ls)
Name: agent-wawR6snj
Address: 
Region:  
Size:    
State:   error
Error:   image 'ubuntu-16.04' not found (invalid_input)
```

My guess is hetzner deprecated the ubuntu 16.04 image.

I was able to fix this by setting the `DRONE_HETZNERCLOUD_IMAGE` environment variable to `ubuntu-20.04` - I think the default should be set to 20.04. I could send a PR if you'd accept one.

### PR DESCRIPTION
**Pull request by kolaente**
Fixes #99

### CODE REVIEW

**Comment by xsteadfastx** [comment]
would be so happy if this gets merged!

**Comment by xsteadfastx** [comment]
oh i see... `provider_test.go` still needs to be fixed.

**Comment by kolaente** [comment]
Test is fixed. @bradrydzewski  @eoinmcafee00 any chance to get this merged?

**Comment by eoinmcafee00** [comment]
Thanks, @kolaente 
This has now been merged.

**Pull request merged**
